version: "3.9"

services:
  server:
    build: .
    container_name: server
    volumes:
      - .:/code
    env_file:
      - .env
    command: uvicorn adbk.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
